services:
  db:
    container_name: tta_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travelAnalyzer
    ports:
      - '5433:5431'
    command: "-p 5431"
  app:
    build: ./
    container_name: tta_app
    command: sh -c "sleep 3s; python3 main.py"
    depends_on:
      - db
