services:
  tta_db:
    build: ./db/
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travelAnalyzer
    ports:
      - '5432:5432'
  tta_app:
    build: ./
    command: sh -c "sleep 1s; python3 main.py"
    depends_on:
      - tta_db
